config/routes.rb
SampleApp110811::Application.routes.draw do
  get "users/new"

  root :to => 'pages#home'
  match '/contact', :to => 'pages#contact'
  match '/about', :to => 'pages#about'
  match '/help', :to => 'pages#help'
  match '/signup', :to => 'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
  end

  def contact
    @title = "Contact"
  end
  
  def about
    @title = "About"
  end
  
  def help
    @title = "Help"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def logo
    image_tag("logo.png", :alt => "Kays App", :class => "round")
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
 <footer>
	<nav class = "round" >
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "News", 'http://news.railstutorial.org' %></li>
			<li><%= link_to "Rails tutorial", 'http://railstutorial.org' %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= link_to logo, root_path %>
	<nav class ="round" >
		<ul>
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "Help", help_path %></li>
			<li><%= link_to "Sign in", '#' %> </li>
	    </ul>
	</nav>
</header>

app/views/layouts/_stylesheets.html.erb
<%= stylesheet_link_tag    'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag    'blueprint/print', :media => 'print' %>
<%= stylesheet_link_tag    'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title %></title>
  <%= render 'layouts/stylesheets' %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
      <%= render 'layouts/header' %>
      <section class = "round" >
          <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<%= link_to "Sign up now!", '#', :class => "signup_button round" %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>